[header]
defFont=GB10
genEnglish=1
genChinese=1
lastOpenFile=C:\Documents and Settings\ABC\桌面\languages.msg
lastSaveFile=
count=17
[1]
macro=HINT_SPLASH
English=
Chinese=EVACC_Tester 版本v1.0
[2]
macro=HINT_NO_YES
English=
Chinese=*=否           #=是
[3]
macro=HINT_CANCEL_CONFIRM
English=
Chinese=*=取消        #=确认
[4]
macro=HINT_RET_DN_CONFIRM
English=
Chinese=*=返回 0,8=翻页 #=确认
[5]
macro=HINT_UP_DN
English=
Chinese=8=上页      0=下页
[6]
macro=HINT_RET_UP_DN
English=
Chinese=*=返回 8=上页 0=下页
[7]
macro=HINT_CANCEL_DN_UPDATE
English=
Chinese=*=取消 0,8=翻页 #=更新
[8]
macro=HINT_BACK_CONFIRM
English=
Chinese=*=后退        #=确认
[9]
macro=HINT_CANCEL_UPDATE
English=
Chinese=*=取消        #=更新
[10]
macro=HINT_RET
English=
Chinese=*=返回
[11]
macro=HINT_CHG_BAR
English=
Chinese=*=取消 7,9=改变 #=确认
[12]
macro=HINT_MOVEMENT
English=
Chinese=7,8,9,0=移动   #=确认
[13]
macro=SYS_TIME
English=
Chinese=
[14]
macro=UNIT_MSEC
English=
Chinese=毫秒
[15]
macro=UNIT_SEC
English=
Chinese=秒
[16]
macro=UNIT_PCS
English=
Chinese=个
[17]
macro=MSG_ABOUT
English=
Chinese=关于
