[header]
defFont=GB12
genEnglish=1
genChinese=1
lastOpenFile=C:\Documents and Settings\ABC\桌面\evacc3.0 language\languages.msg
lastSaveFile=
count=34
[1]
macro=HINT_SPLASH
English=EVACC v3.0
Chinese=EVACC  v3.0
[2]
macro=UNIT_SEC
English=s
Chinese=秒
[3]
macro=UINT_MIN
English=min
Chinese=分钟
[4]
macro=UINT_HOUR
English=hr
Chinese=小时
[5]
macro=UNIT_CURRENT
English=A
Chinese=A
[6]
macro=UNIT_ENERGY
English=KWh
Chinese=KWh
[7]
macro=UINT_TEMP
English=C
Chinese=C
[8]
macro=UNIT_CCY
English=$
Chinese=￥
[9]
macro=MSG_TIME
English=TIME ELASPED
Chinese=耗时
[10]
macro=MSG_FEE
English=FREE
Chinese=费用
[11]
macro=MSG_CREDIT
English=CREDIT
Chinese=余额
[12]
macro=MSG_MAKE_KEY_CARD
English=CHECK A NEW CARD;TO MAKE;PRIVATE CARD
Chinese=拍新卡;创建;私有设定卡
[13]
macro=MSG_READ_CARD_EEROR
English=READ CARD ERROR
Chinese=读卡失败
[14]
macro=MSG_WRITE_CARD_ERROR
English=WRITE CARD ERROR
Chinese=写卡失败
[15]
macro=MSG_FEE_UNPAID
English=FEE UNPAID;CONTACT;CUSTOMER SERVICE;PLEASE
Chinese=欠费;请联系;客户服务
[16]
macro=MSG_INSUFFICIENT_BALANCE
English=INSUFFICIENT BALANCE
Chinese=余额不足
[17]
macro=MSG_CARD_BALANCE
English=CARD BALANCE
Chinese=卡内余额
[18]
macro=MSG_PLUG_IN_CHARGE_GUN
English=PLUG IN;CHARGING GUN;TO;START
Chinese=请把充电枪;插入;汽车充电座
[19]
macro=MSG_HANDSHAKING
English=TALKING TO;VEHICLE;ONE MOMENT;PLEASE
Chinese=与车辆;通讯中;请稍侯片刻
[20]
macro=MSG_UNPLUG_TO_PAY
English=UNPLUG;CHARGING GUN;TO;CHECK OUT
Chinese=请拔出;充电枪;结账
[21]
macro=MSG_CHECK_CARD_TO_PAY
English=CHECK CARD TO PAY
Chinese=拍卡付款
[22]
macro=MSG_OPEN_APP_TO_PAY
English=OPEN APP TO PAY
Chinese=打开APP付款
[23]
macro=MSG_PARKING
English=PARKING
Chinese=泊
[24]
macro=MSG_ENERGY
English=ENERGY
Chinese=电
[25]
macro=MSG_PENALTY
English=PENALTY
Chinese=罚款
[26]
macro=MSG_TOTAL
English=TOTAL
Chinese=总计
[27]
macro=MSG_PAID
English=PAID
Chinese=已付
[28]
macro=MSG_BALANCE
English=BALANCE
Chinese=余额
[29]
macro=MSG_LID_OPENED
English=ERROR;LID;IS OPENED
Chinese=故障;面盖;没关好
[30]
macro=MSG_PANIC_BTN_PRESSED
English=ERROR;PANIC BUTTON;IS PRESSED
Chinese=故障:急停按钮;被按下
[31]
macro=MSG_FATAL_ERROR
English=FATAL ERROR!;POWER CYCLE;TO RESET
Chinese=不可修复故障;;需要;电源复位
[32]
macro=MSG_DEBUG_MODE
English=(DEBUG MODE)
Chinese=(除错模式)
[33]
macro=MSG_OVER_TEMP
English=OVER TEMP.
Chinese=温度超限
[34]
macro=MSG_TEMP_OUT_OF_RANGE
English=SERVICE SUSPENDED;OVER TEMPERATURE
Chinese=暂停服务;温度超限
